# Generated by Django 4.1.3 on 2022-12-01 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="check_expected_return_date",
        ),
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="check_actual_return_date",
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("expected_return_date__gt", models.F("borrow_date")),
                    ("expected_return_date__lte", datetime.date(2022, 12, 31)),
                ),
                name="check_expected_return_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(("actual_return_date", datetime.date(2022, 12, 1))),
                name="check_actual_return_date",
            ),
        ),
    ]
